version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8010:80'
#      - '443:443'
    volumes:
      - '../webroot/:/app'
volumes:
  apache_data:
    driver: local
